# Generated by Django 5.2.17 on 2026-09-20 05:01

import catalogo.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='slug')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('ingredientes', models.TextField(verbose_name='ingredientes')),
                ('alergenicos', models.TextField(verbose_name='alergênicos')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='preço')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', validators=[catalogo.validators.validar_imagem], verbose_name='imagem')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='estoque')),
                ('total_vendas', models.PositiveIntegerField(default=0, verbose_name='total de vendas')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nome_busca', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='nome para busca')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['-total_vendas', '-criado_em'],
            },
        ),
    ]
