# Generated by Django 5.2.17 on 2026-09-20 05:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('tipo', models.CharField(choices=[('PERCENTUAL', 'Percentual'), ('FIXO', 'Fixo')], max_length=10, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor')),
                ('valor_minimo_pedido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='valor mínimo do pedido')),
                ('data_validade', models.DateTimeField(verbose_name='data de validade')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'cupom',
                'verbose_name_plural': 'cupons',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TabelaFreteUF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2, unique=True, verbose_name='UF')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='valor')),
                ('prazo_dias', models.PositiveIntegerField(verbose_name='prazo em dias')),
            ],
            options={
                'verbose_name': 'tabela de frete por UF',
                'verbose_name_plural': 'tabelas de frete por UF',
                'ordering': ['uf'],
            },
        ),
        migrations.CreateModel(
            name='CupomUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_uso', models.DateTimeField(auto_now_add=True, verbose_name='data de uso')),
                ('cupom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='pedidos.cupom', verbose_name='cupom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons_usados', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'uso de cupom',
                'verbose_name_plural': 'usos de cupons',
                'ordering': ['-data_uso'],
                'unique_together': {('cupom', 'usuario')},
            },
        ),
    ]
