# Generated by Django 5.2.17 on 2026-09-20 05:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('endereco_entrega', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('valor_frete', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('forma_pagamento', models.CharField(choices=[('CARTAO', 'Cartão'), ('PIX', 'PIX')], max_length=6)),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('EM_PREPARACAO', 'Em preparação'), ('SAIU_PARA_ENTREGA', 'Saiu para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO_PAGAMENTO', max_length=20)),
                ('estoque_baixado', models.BooleanField(default=False)),
                ('pix_expira_em', models.DateTimeField(blank=True, null=True)),
                ('detalhes_pagamento', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cupom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedidos.cupom')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('EM_PREPARACAO', 'Em preparação'), ('SAIU_PARA_ENTREGA', 'Saiu para entrega'), ('ENTREGUE', 'Entregue'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_status', to='pedidos.pedido')),
            ],
            options={
                'ordering': ['criado_em', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=150)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quantidade', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='item_pedido_quantidade_positiva')],
            },
        ),
        migrations.CreateModel(
            name='ReservaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField(db_index=True)),
                ('ativa', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('usuario', 'produto'), name='reserva_usuario_produto_unica'), models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='reserva_quantidade_positiva')],
            },
        ),
    ]
